#use_frameworks!

target 'SDIJKPlayerSSL_Example' do
  pod 'SDIJKPlayerSSL', :path => '../'
  pod 'YYWebImage'
  pod 'Masonry'
  pod 'SVProgressHUD'
  
  target 'SDIJKPlayerSSL_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
  end
end
